receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  otlp:
    endpoint: "http://otel-collector:4317"
  debug: 
    verbosity: detailed

processors:
  batch:
    timeout: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
